const express = require('express');
const { z } = require('zod');

const app = express();
const port = 3000;

// CRITICAL: Middleware to parse incoming JSON payloads
app.use(express.json());

let users = [];
let nextId = 1;

// Renamed to avoid variable shadowing, and removed 'id' 
// since it is generated by the server.
const userSchema = z.object({
  name: z.string(),
  age: z.number().int().positive() // Added .int() and .positive() for better validation
});
app.get('/', (req, res) => {
  res.send('Hello World!');
});
app.get('/users', (req, res) => {
  res.json(users);
});

app.post('/users', (req, res, next) => {
  try {
    // Validate incoming data
    const data = userSchema.parse(req.body);
    
    // Create the new user with a server-generated ID
    const newUser = { id: nextId++, ...data };
    users.push(newUser);
    
    res.status(201).json(newUser);
  } catch (err) {
    next(err); 
  }
});

app.delete("/users/:id", (req, res) => {
  const id = parseInt(req.params.id, 10);
  const idx = users.findIndex(u => u.id === id);
  
  if (idx === -1) {
    return res.status(404).json({ error: "Not found" });
  }
  
  users.splice(idx, 1);
  res.status(204).send();
});

// Global error handler
app.use((err, req, res, next) => {
  // Using instanceof is the recommended way to check for Zod errors
  if (err instanceof z.ZodError) {
    return res.status(400).json({ error: err.errors });
  }
  
  console.error(err); // Log the error for server-side debugging
  res.status(500).json({ error: "Internal server error" });
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});